language: python
python:
- 3.8
sudo: required
dist: xenial
notifications:
  email: false
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb python3-pyqt5 python3-pyqt5.qtmultimedia
install:
  - python setup.py install
  - pip install coverage
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-faulthandler
  - pip install pytest-mock
  - pip install pytest-qt
  - pip install pytest-xvfb
script:
  - py.test -s -v --cov=./
after_success:
  - coveralls